name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Tests unitaires
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Exécuter les tests unitaires
        run: |
          python -m unittest discover -s tests -v


  e2e-tests:
    name: Tests E2E
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Démarrer l'application
        run: |
          python app.py &
          sleep 5

      - name: Exécuter les tests E2E
        run: |
          pytest e2e/ -v


